# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/mte90/Desktop/Prog/Penmode-Qt/mainWindow.ui'
#
# Created: Wed Apr 24 01:06:09 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(649, 480)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_2.addWidget(self.pushButton, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 2, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_2.addWidget(self.pushButton_2, 0, 3, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_whatweb = QtGui.QWidget()
        self.tab_whatweb.setObjectName(_fromUtf8("tab_whatweb"))
        self.tabWidget.addTab(self.tab_whatweb, _fromUtf8(""))
        self.tab_nmap = QtGui.QWidget()
        self.tab_nmap.setObjectName(_fromUtf8("tab_nmap"))
        self.tabWidget.addTab(self.tab_nmap, _fromUtf8(""))
        self.tab_nikto = QtGui.QWidget()
        self.tab_nikto.setObjectName(_fromUtf8("tab_nikto"))
        self.tabWidget.addTab(self.tab_nikto, _fromUtf8(""))
        self.tab_joomscan = QtGui.QWidget()
        self.tab_joomscan.setObjectName(_fromUtf8("tab_joomscan"))
        self.tabWidget.addTab(self.tab_joomscan, _fromUtf8(""))
        self.tab_wpscan = QtGui.QWidget()
        self.tab_wpscan.setObjectName(_fromUtf8("tab_wpscan"))
        self.tabWidget.addTab(self.tab_wpscan, _fromUtf8(""))
        self.tab_skipfish = QtGui.QWidget()
        self.tab_skipfish.setObjectName(_fromUtf8("tab_skipfish"))
        self.tabWidget.addTab(self.tab_skipfish, _fromUtf8(""))
        self.tab_sqlmap = QtGui.QWidget()
        self.tab_sqlmap.setObjectName(_fromUtf8("tab_sqlmap"))
        self.tabWidget.addTab(self.tab_sqlmap, _fromUtf8(""))
        self.tab_slowloris = QtGui.QWidget()
        self.tab_slowloris.setObjectName(_fromUtf8("tab_slowloris"))
        self.tabWidget.addTab(self.tab_slowloris, _fromUtf8(""))
        self.tab_exploit = QtGui.QWidget()
        self.tab_exploit.setObjectName(_fromUtf8("tab_exploit"))
        self.tabWidget.addTab(self.tab_exploit, _fromUtf8(""))
        self.tab_dork = QtGui.QWidget()
        self.tab_dork.setObjectName(_fromUtf8("tab_dork"))
        self.tabWidget.addTab(self.tab_dork, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 649, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        MainWindow.setMenuBar(self.menubar)
        self.actionSocat = QtGui.QAction(MainWindow)
        self.actionSocat.setObjectName(_fromUtf8("actionSocat"))
        self.actionTor = QtGui.QAction(MainWindow)
        self.actionTor.setObjectName(_fromUtf8("actionTor"))
        self.actionWhatWeb = QtGui.QAction(MainWindow)
        self.actionWhatWeb.setObjectName(_fromUtf8("actionWhatWeb"))
        self.actionNmap = QtGui.QAction(MainWindow)
        self.actionNmap.setObjectName(_fromUtf8("actionNmap"))
        self.actionNikto = QtGui.QAction(MainWindow)
        self.actionNikto.setObjectName(_fromUtf8("actionNikto"))
        self.actionJoomScan = QtGui.QAction(MainWindow)
        self.actionJoomScan.setObjectName(_fromUtf8("actionJoomScan"))
        self.actionWpScan = QtGui.QAction(MainWindow)
        self.actionWpScan.setObjectName(_fromUtf8("actionWpScan"))
        self.actionSkipFish = QtGui.QAction(MainWindow)
        self.actionSkipFish.setObjectName(_fromUtf8("actionSkipFish"))
        self.actionSqlmap = QtGui.QAction(MainWindow)
        self.actionSqlmap.setObjectName(_fromUtf8("actionSqlmap"))
        self.actionAbout_Penmode = QtGui.QAction(MainWindow)
        self.actionAbout_Penmode.setObjectName(_fromUtf8("actionAbout_Penmode"))
        self.actionAbout_Phos = QtGui.QAction(MainWindow)
        self.actionAbout_Phos.setObjectName(_fromUtf8("actionAbout_Phos"))
        self.menuHelp.addAction(self.actionSocat)
        self.menuHelp.addAction(self.actionTor)
        self.menuHelp.addAction(self.actionWhatWeb)
        self.menuHelp.addAction(self.actionNmap)
        self.menuHelp.addAction(self.actionNikto)
        self.menuHelp.addAction(self.actionJoomScan)
        self.menuHelp.addAction(self.actionWpScan)
        self.menuHelp.addAction(self.actionSkipFish)
        self.menuHelp.addAction(self.actionSqlmap)
        self.menuAbout.addAction(self.actionAbout_Penmode)
        self.menuAbout.addSeparator()
        self.menuAbout.addAction(self.actionAbout_Phos)
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(9)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.pushButton.setText(_translate("MainWindow", "Enable", None))
        self.label.setText(_translate("MainWindow", "Socat", None))
        self.label_2.setText(_translate("MainWindow", "Tor", None))
        self.pushButton_2.setText(_translate("MainWindow", "Enable", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_whatweb), _translate("MainWindow", "WhatWeb", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_nmap), _translate("MainWindow", "Nmap", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_nikto), _translate("MainWindow", "Nikto", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_joomscan), _translate("MainWindow", "JoomScan", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_wpscan), _translate("MainWindow", "WpScan", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_skipfish), _translate("MainWindow", "SkipFish", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_sqlmap), _translate("MainWindow", "SqlMap", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_slowloris), _translate("MainWindow", "SlowLoris", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_exploit), _translate("MainWindow", "Exploit", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_dork), _translate("MainWindow", "Dork", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.menuAbout.setTitle(_translate("MainWindow", "About", None))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings", None))
        self.actionSocat.setText(_translate("MainWindow", "Socat", None))
        self.actionTor.setText(_translate("MainWindow", "Tor", None))
        self.actionWhatWeb.setText(_translate("MainWindow", "WhatWeb", None))
        self.actionNmap.setText(_translate("MainWindow", "Nmap", None))
        self.actionNikto.setText(_translate("MainWindow", "Nikto", None))
        self.actionJoomScan.setText(_translate("MainWindow", "JoomScan", None))
        self.actionWpScan.setText(_translate("MainWindow", "WpScan", None))
        self.actionSkipFish.setText(_translate("MainWindow", "SkipFish", None))
        self.actionSqlmap.setText(_translate("MainWindow", "Sqlmap", None))
        self.actionAbout_Penmode.setText(_translate("MainWindow", "About Penmode", None))
        self.actionAbout_Phos.setText(_translate("MainWindow", "About Phos", None))

